<?php

namespace WPSPCORE\App\Widen\Support\Facades;

if (class_exists('Illuminate\Support\Facades\Request')) {
	class Request extends \Illuminate\Support\Facades\Request {}
}
else {
	/**
	 * Facade cho 'request' - mô phỏng Illuminate\Support\Facades\Request.
	 *
	 * Gọi static:  Request::input('id'), Request::get('page'), Request::all(), Request::file('avatar')
	 * Lấy object:  Request::instance() hoặc Request::getFacadeRoot()
	 *
	 * Không dùng class này làm type-hint cho DI; hãy type-hint
	 * \WPSPCORE\App\Widen\Http\Request (giống Laravel: type-hint Illuminate\Http\Request).
	 *
	 * @method static \WPSPCORE\App\Widen\Http\Request resetCache()
	 * @method static \WPSPCORE\App\Widen\Http\Request duplicate(?array $query = null, ?array $request = null, ?array $attributes = null, ?array $cookies = null, ?array $files = null, ?array $server = null)
	 * @method static string getRealMethod()
	 * @method static string getMethod()
	 * @method static string method()
	 * @method static void setMethod(string $method)
	 * @method static bool isMethod(string $method)
	 * @method static bool isMethodSafe()
	 * @method static bool isMethodIdempotent()
	 * @method static bool isMethodCacheable()
	 * @method static \WPSPCORE\App\Widen\Http\Request setBaseUrl(string $baseUrl)
	 * @method static string getBaseUrl()
	 * @method static string getBasePath()
	 * @method static string getScriptName()
	 * @method static string getRequestUri()
	 * @method static string getPathInfo()
	 * @method static string path()
	 * @method static string decodedPath()
	 * @method static array segments()
	 * @method static mixed segment(int $index, $default = null)
	 * @method static string getQueryString()
	 * @method static string getScheme()
	 * @method static string getHttpHost()
	 * @method static string getHost()
	 * @method static int getPort()
	 * @method static string getSchemeAndHttpHost()
	 * @method static string getUri()
	 * @method static ?string getUser()
	 * @method static ?string getPassword()
	 * @method static ?string getUserInfo()
	 * @method static ?string getProtocolVersion()
	 * @method static string root()
	 * @method static string url()
	 * @method static string fullUrl()
	 * @method static string fullUrlWithQuery(array $query)
	 * @method static string fullUrlWithoutQuery(array|string $keys)
	 * @method static mixed uri()
	 * @method static bool is(string ...$patterns)
	 * @method static bool fullUrlIs(string ...$patterns)
	 * @method static bool routeIs(string ...$patterns)
	 * @method static string host()
	 * @method static string httpHost()
	 * @method static string schemeAndHttpHost()
	 * @method static bool isFromTrustedProxy()
	 * @method static bool isSecure()
	 * @method static bool secure()
	 * @method static array getClientIps()
	 * @method static ?string getClientIp()
	 * @method static array ips()
	 * @method static ?string ip()
	 * @method static ?string userAgent()
	 * @method static bool ajax()
	 * @method static bool isXmlHttpRequest()
	 * @method static bool pjax()
	 * @method static bool prefetch()
	 * @method static mixed header(?string $key = null, $default = null)
	 * @method static bool hasHeader(string $key)
	 * @method static ?string bearerToken()
	 * @method static ?string getContentType()
	 * @method static ?string getContentTypeFormat()
	 * @method static ?string getMimeType(string $format)
	 * @method static ?string getFormat(?string $mimeType)
	 * @method static ?string getRequestFormat(?string $default = 'html')
	 * @method static void setRequestFormat(?string $format)
	 * @method static bool isJson()
	 * @method static array getAcceptableContentTypes()
	 * @method static array getCharsets()
	 * @method static array getEncodings()
	 * @method static array getETags()
	 * @method static bool isNoCache()
	 * @method static bool preferSafeContent()
	 * @method static ?string getPreferredFormat(?string $default = 'html')
	 * @method static bool expectsJson()
	 * @method static bool wantsJson()
	 * @method static bool accepts(array|string $contentTypes)
	 * @method static ?string prefers(array|string $contentTypes)
	 * @method static bool acceptsAnyContentType()
	 * @method static bool acceptsJson()
	 * @method static bool acceptsHtml()
	 * @method static bool matchesType(string $actual, string $type)
	 * @method static string format(string $default = 'html')
	 * @method static array getLanguages()
	 * @method static ?string getPreferredLanguage(?array $locales = null)
	 * @method static string getLocale()
	 * @method static void setLocale(string $locale)
	 * @method static string getDefaultLocale()
	 * @method static void setDefaultLocale(string $locale)
	 * @method static void setRequestLocale(string $locale)
	 * @method static void setDefaultRequestLocale(string $locale)
	 * @method static string getContent()
	 * @method static mixed json(?string $key = null, $default = null)
	 * @method static \WPSPCORE\App\Widen\Http\Request setJson(WPSPCORE\App\Widen\Http\ParameterBag $json)
	 * @method static mixed server(?string $key = null, $default = null)
	 * @method static array all($keys = null)
	 * @method static mixed input(?string $key = null, $default = null)
	 * @method static mixed query(?string $key = null, $default = null)
	 * @method static mixed post(?string $key = null, $default = null)
	 * @method static array keys()
	 * @method static bool exists(...$keys)
	 * @method static bool has(...$keys)
	 * @method static bool hasAny(...$keys)
	 * @method static bool missing(...$keys)
	 * @method static bool filled(...$keys)
	 * @method static bool isNotFilled(...$keys)
	 * @method static bool anyFilled(...$keys)
	 * @method static mixed whenHas(string $key, callable $callback, ?callable $default = null)
	 * @method static mixed whenFilled(string $key, callable $callback, ?callable $default = null)
	 * @method static mixed whenMissing(string $key, callable $callback, ?callable $default = null)
	 * @method static mixed str(string $key, $default = null)
	 * @method static mixed string(string $key, $default = null)
	 * @method static bool boolean(?string $key = null, bool $default = false)
	 * @method static int integer(string $key, int $default = 0)
	 * @method static float float(string $key, float $default = 0.0)
	 * @method static mixed date(string $key, ?string $format = null, ?string $tz = null)
	 * @method static mixed enum(string $key, string $enumClass, $default = null)
	 * @method static array enums(string $key, string $enumClass)
	 * @method static mixed collect($key = null)
	 * @method static array only(...$keys)
	 * @method static array except(...$keys)
	 * @method static \WPSPCORE\App\Widen\Http\Request merge(array $input)
	 * @method static \WPSPCORE\App\Widen\Http\Request mergeIfMissing(array $input)
	 * @method static \WPSPCORE\App\Widen\Http\Request replace(array $input)
	 * @method static mixed get(string $key, mixed $default = null)
	 * @method static \WPSPCORE\App\Widen\Http\Request dump(...$keys)
	 * @method static mixed dd(...$keys)
	 * @method static bool hasCookie(string $key)
	 * @method static mixed cookie(?string $key = null, $default = null)
	 * @method static array allFiles()
	 * @method static mixed file(?string $key = null, $default = null)
	 * @method static bool hasFile(string $key)
	 * @method static bool hasSession(bool $skipIfUninitialized = false)
	 * @method static mixed getSession()
	 * @method static mixed session()
	 * @method static void setLaravelSession($session)
	 * @method static void setSession($session)
	 * @method static mixed old(?string $key = null, $default = null)
	 * @method static void flash()
	 * @method static void flashOnly(...$keys)
	 * @method static void flashExcept(...$keys)
	 * @method static void flush()
	 * @method static bool isAttemptingPrecognition()
	 * @method static bool isPrecognitive()
	 * @method static mixed user($guard = null)
	 * @method static \Closure getUserResolver()
	 * @method static \WPSPCORE\App\Widen\Http\Request setUserResolver(\Closure $callback)
	 * @method static mixed route(?string $param = null, $default = null)
	 * @method static \Closure getRouteResolver()
	 * @method static \WPSPCORE\App\Widen\Http\Request setRouteResolver(\Closure $callback)
	 * @method static string fingerprint()
	 * @method static mixed when($value = null, ?callable $callback = null, ?callable $default = null)
	 * @method static mixed unless($value = null, ?callable $callback = null, ?callable $default = null)
	 * @method static array toArray()
	 *
	 * @see \WPSPCORE\App\Widen\Http\Request
	 */
	class Request extends Facade {

		protected static function getFacadeAccessor() {
			return 'request';
		}

		/**
		 * Object request thật (Laravel: Request::instance()).
		 *
		 * @return \WPSPCORE\App\Widen\Http\Request
		 */
		public static function instance() {
			return static::getFacadeRoot();
		}

	}
}